import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F2F2F2]">
        <Header />
        <main className="h-full flex mx-5 md:mx-[12rem] my-6">{children}</main>
      </body>
    </html>
  );
}
